# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Импортируем специальный скрипт Flutter для подключения всех необходимых pod'ов
  flutter_application_path = '../'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  install_all_flutter_pods(flutter_application_path)
end